
// page titles

STRING_DEFINE(HOME,"Home")
STRING_DEFINE(DOWNLOADS,"Downloads")
STRING_DEFINE(FAQ,"FAQ")
STRING_DEFINE(SUPPORT,"Support")
STRING_DEFINE(FORUMS,"Forums")
STRING_DEFINE(DONATE,"Donate")
STRING_DEFINE(CONTACT,"Contact")
STRING_DEFINE(PRIVACY,"Privacy")
STRING_DEFINE(ERROR404,"ERROR 404")
STRING_DEFINE(ABOUT,"About voidtools")
STRING_DEFINE(LANGUAGE,"Language")
STRING_DEFINE(DONATED,"Donated")
STRING_DEFINE(CONTACTOK,"CONTACT Successful")
STRING_DEFINE(CONTACTERROR,"CONTACT Error")
STRING_DEFINE(UPDATE,"Update")
STRING_DEFINE(MAINTENANCE,"Maintenance")

// templates

STRING_DEFINE(HOME_TEMPLATE,"home.txt")
STRING_DEFINE(DOWNLOADS_TEMPLATE,"downloads.txt")
STRING_DEFINE(FAQ_TEMPLATE,"faq.txt")
STRING_DEFINE(DONATE_TEMPLATE,"donate.txt")
STRING_DEFINE(ERROR404_TEMPLATE,"error404.txt")
STRING_DEFINE(CONTACT_TEMPLATE,"contact.txt")
STRING_DEFINE(PRIVACY_TEMPLATE,"privacy.txt")
STRING_DEFINE(ABOUT_TEMPLATE,"about.txt")
STRING_DEFINE(LANGUAGE_TEMPLATE,"language.txt")
STRING_DEFINE(DONATED_TEMPLATE,"donated.txt")
STRING_DEFINE(CONTACTOK_TEMPLATE,"contactok.txt")
STRING_DEFINE(CONTACTERROR_TEMPLATE,"contacterror.txt")
STRING_DEFINE(UPDATE_TEMPLATE,"update.txt")
STRING_DEFINE(MAINTENANCE_TEMPLATE,"maintenance.txt")

// Support wiki

STRING_DEFINE(SUPPORT_FOLDER,"support")

// License template.

STRING_DEFINE(LICENSE_TEMPLATE,"License.txt")

// URLS

STRING_DEFINE(SUPPORT_URL,"support/everything")
STRING_DEFINE(FORUMS_URL,"/forum")

// titles
	
STRING_DEFINE(HOME_TITLE,"voidtools")
STRING_DEFINE(TITLE_FORMAT,"{{TITLE}} - voidtools")

// Download page

STRING_DEFINE(DOWNLOAD_EVERYTHING_HEADER,"Download Everything {{VERSION}}")
STRING_DEFINE(EVERYTHING_CHANGES,"[[{{CHANGES}}|Changes]]")
STRING_DEFINE(EVERYTHING_OLDER_VERSIONS,"[[support/everything/previous_versions/|Older Versions]]")
STRING_DEFINE(EVERYTHING_LICENSE,"[[License.txt|License]]")
STRING_DEFINE(EVERYTHING_MD5,"[[{{MD5}}|MD5]]")
STRING_DEFINE(EVERYTHING_SHA256,"[[{{SHA256}}|SHA256]]")
STRING_DEFINE(EVERYTHING_SUPPORTED_LANGUAGES,"[[support/everything/supported_languages/|Supported Languages]]" )
STRING_DEFINE(EVERYTHING_HELP,"[[support/everything/installing_everything/|Help]]")

STRING_DEFINE(DOWNLOAD_EVERYTHING_BETA_HEADER,"Download Everything {{VERSION}} Beta")
STRING_DEFINE(EVERYTHING_BETA_WHATS_NEW,"[[support/everything/whats_new|What's New]]")

STRING_DEFINE(DOWNLOAD_INSTALLER,"Download Installer")
STRING_DEFINE(DOWNLOAD_INSTALLER_X64,"Download Installer 64-bit")
STRING_DEFINE(DOWNLOAD_PORTABLE_ZIP,"Download Portable Zip")
STRING_DEFINE(DOWNLOAD_PORTABLE_ZIP_X64,"Download Portable Zip 64-bit")

STRING_DEFINE(ALL_EVERYTHING_DOWNLOADS_HEADER,"All Everything Downloads")
STRING_DEFINE(INSTALLER,"Installer")
STRING_DEFINE(PORTABLE,"Portable")
STRING_DEFINE(MULTILINGUAL,"[[support/everything/supported_languages|Multilingual]]")
STRING_DEFINE(KB,"KB")

STRING_DEFINE(DOWNLOAD_EVERYTHING_LANGUAGE_PACK_HEADER,"Download Everything Language Pack")
STRING_DEFINE(EVERYTHING_LANGUAGE_PACK_HELP,"[[support/everything/supported_languages/#installing_the_language_pack|Help]]")

STRING_DEFINE(DOWNLOAD_EVERYTHING_COMMAND_LINE_INTERFACE_HEADER,"Download Everything Command-line Interface")
STRING_DEFINE(EVERYTHING_COMMAND_LINE_INTERFACE_HELP,"[[support/everything/command_line_interface|Help]]")

STRING_DEFINE(DOWNLOAD_EVERYTHING_SDK_HEADER,"Download Everything SDK")
STRING_DEFINE(EVERYTHING_SDK_HELP,"[[support/everything/SDK|Help]]")

// footer

STRING_DEFINE(COPYRIGHT,"&copy; {{YEAR}} - ")

// donate
STRING_DEFINE(DONATE_FORM_NAME,"Name (optional, name will be published below, leave blank for an anonymous donation):")
STRING_DEFINE(DONATE_FORM_COMMENT,"Comment (optional, 200 characters max):")
STRING_DEFINE(DONATE_FORM_BUTTON_IMAGE,"paypal.donate.png")
STRING_DEFINE(DONATE_FORM_DONATE,"Donate")
STRING_DEFINE(DONATE_HISTORY,"Donation History")
STRING_DEFINE(DONATE_HISTORY_NAME,"Name")
STRING_DEFINE(DONATE_HISTORY_COMMENT,"Comment")
STRING_DEFINE(DONATE_HISTORY_AMOUNT,"Amount")

// contact

STRING_DEFINE(CONTACT_FORM_MESSAGE,"Message:")
STRING_DEFINE(CONTACT_FORM_EMAIL,"Email (optional):")
STRING_DEFINE(CONTACT_FORM_SEND,"Send")

STRING_DEFINE(DOWNLOAD_EVERYTHING_OFFLINE_HELP,"Download Everything Offline Help")



